# Macro file
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run.mac
#
/run/initialize
#
# Define the beam (photons)
# Particle
/gps/particle gamma
/gps/energy 200 keV
/gps/direction 0.0  0.0 1.0
/gps/polarization 1. 0. 0.
# Beam
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0.0 0.0 -300.0 cm
/gps/pos/halfx 50.0 cm
/gps/pos/halfy 50.0 cm
# Run
/run/beamOn 2000
